version: "2.1"

services:
  notifier:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      MYSQL_DATABASE: ${MYSQL_NAME}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE_HOST: db
      MYSQL_DATABASE_PORT: 3306
      WORKER_CONNECTIONS: ${WORKER_CONNECTIONS}
      WORKER_TIMEOUT: ${WORKER_TIMEOUT}
      WORKERS: ${WORKERS}
      TZ: ${TZ}
    restart: always
    volumes:
      - static_data:/app/static/
      - ./wplusnotifier/:/app/wplusnotifier/
      - ${DATA_VOL}:/app/attachments/
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${BACKEND_PORT}:80"
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${PMA_PORT}:80"
    restart: unless-stopped
  db:
    image: mariadb
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${MYSQL_NAME}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      timeout: 10s
      retries: 10

volumes:
  mysql_data:
  static_data:
